### ISSUE TITLE
Ability to import our project into a project with react components, find all react components and generate tests for them.

### ISSUE THREAD

**Issue by TheRobban02** [Erikborgis/react-automatic-testing#21]
Removes the need for adding react components to a certain folder and makes our "pipeline" more like a usable tool

**Comment by TheRobban02** [comment]
Not tested within another project but works well in the react-automatic-testing. Can now navigate to root which in this case is react-automatic-testing, it the finds react components spread out in different folders throughout the project and creates tests for them. Added react component path to the gpt prompt since that now can be different for different components.

**Comment by Erikborgis** [comment]
Do we really want it to always generate tests for a whole project?
